Lazy
GolrovKirill/SPbU-Prog3 pull request #2
Opened 2024-10-17 01:30 UTC by GolrovKirill

2024-10-24 21:21 UTC, ArtyomKopan reviewed
2/5. Не рассмотрены плохие случаи, например, когда supplier выбрасывает исключение. Хорошая идея --- хранить это исключение в Lazy, и выбрасывать его, когда потребуется

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy.Tests/LazyTest.cs
> +    private const double Equal = 0.0000001;
не очень удачное название. Equal --- это прилагательное, а переменные и константы нужно называть существительными. Лучше назови эту константу epsilon, например

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy/MultipleLazy.cs
> +public class MultipleLazy<T>(Func<T> supplier) : ILazy<T>
опять же, название не очень удачное. MultipleLazy = множественное Lazy --- непонятно, в каком смысле множественное. Лучше MultiThreadLazy или ThreadSafeLazy

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy/MultipleLazy.cs
> +    public bool FlagResult { get; private set; }
зачем делать это поле публичным? По логике, оно должно использоваться только внутри класса MultipleLazy. И его нужно сделать volatile

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy/MultipleLazy.cs
> +            {
Здесь ещё раз надо проверить, что значение еще не вычислено. Если несколько потоков одновременно дойдут до блокировки, то оба вычислят функцию (-0.5)

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy/SingleLazy.cs
> +    public bool FlagResult { get; private set; }
это поле можно сделать приватным. И да, название должно отражать, для чего нужна переменная. Булевские переменные обычно называют is<что-то>, was<что-то>, have<что-то> и т. д. В нашем случае можно назвать переменную isCalculated, isComputed или isEvaluated, и её смысл станет более прозрачным

2024-10-24 21:21 UTC, ArtyomKopan commented on MatrixMultiply/MatrixMultiply.Tests/MultiplicationTest.cs
У тебя сюда попали файлы первой домашки. Их нужно удалить

2024-10-24 21:21 UTC, ArtyomKopan commented on Lazy/Lazy.Tests/LazyTest.cs
> +        Assert.That(!lazy.FlagResult);
А вот так тестировать не надо. Внешний пользователь не должен знать, что у Lazy есть поле FlagResult. Для него Lazy --- это некоторая абстракция, которая просто вычисляет значение функции, которую ей передают, и гарантированно делает это только один раз. А как там используется FlagResult, пользователю безразлично. Собственно, это называется _абстракция_ и _инкапсуляция_.
А тестировать можно так: стоит завести внешний счетчик, к которому в Lazy-вычислении прибавляется единица. И проверить, что после нескольких вызовов счетчик равен единице. Или можно в Lazy-вычислении генерировать случайное число, и проверять, что ответы в обоих случаях получаются одинаковыми

2024-12-03 12:49 UTC, yurii-litvinov requested changes

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy.Tests/LazyTest.cs
> +namespace Lazy.Tests;
Надо ещё шапку с информацией о лицензии

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy.Tests/LazyTest.cs
> +            Assert.That(result, Is.EqualTo("Hello, World!"));
Это не доказывает, что это буквально то же значение. Может, supplier вызывался тысячу раз и возвращал всегда одну и ту же строку, потому что это просто константная строка. Да и Is.EqualTo для строк будет использовать переопределённый оператор `==`, так что даже если вдруг это каким-то образом были бы разные строки с одинаковым значением, они бы всё равно были бы равны. 

Даже `new object` было бы более показательно.

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/ILazy.cs
> +namespace Lazy;
Вот, например, StyleCop выдаёт предупреждения по поводу заголовка с лицензией, а надо, чтобы проект собирался без предупреждений. Тут и везде предупреждения надо либо поправить, либо отключить.

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/ILazy.cs
> +public interface ILazy<T>
```suggestion
public interface ILazy<out T>
```
Если есть возможность указать вариантность, надо её указывать — так пользоваться контейнером будет удобнее.

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadLazy.cs
> +    }
```suggestion
    public MultiThreadLazy(Func<T> supplier)
        => this.supplier = supplier ?? throw new ArgumentNullException(nameof(supplier));
```

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadLazy.cs
> +                    result = supplier();
После вычисления supplier надо занулить, чтобы сборщик мусора мог собрать и его, и всё, что попало к нему в замыкание

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadLazy.cs
> +                    throw new InvalidOperationException("Error while executing supplier function.", ex);
Исключение стоило бы запомнить и кидать каждый раз, когда делается Get(), чтобы не оставлять Lazy в неконсистентном состоянии, когда isCalculated вроде true, а значения нет.

2024-12-03 12:49 UTC, yurii-litvinov commented on Lazy/Lazy/MultiThreadLazy.cs
> +                    isCalculated = true;
isCalculated должен быть volatile (либо должны быть стратегически расставлены операции volatile-чтения/записи). Иначе эту запись другой поток может увидеть до записи в result в строке 34, и исполнить строки 23-25, вернув null к большому удивлению вызывающего.

2025-03-02 21:20 UTC, ArtyomKopan approved these changes
Всё хорошо, 5/5

2025-03-03 08:10 UTC, merged